#!/bin/zsh

APP_PRODUCT_NAME="Free Markdown Viewer"
APP_PROJECT_DIR_NAME="Free Markdown Viewer"
APP_PROJECT_FILE_NAME="Free Markdown Viewer.xcodeproj"
APP_SCHEME_NAME="Free Markdown Viewer"
APP_BUNDLE_IDENTIFIER="com.souschefstudio.Free-Markdown-Viewer"
APP_UNIT_TEST_TARGET_NAME="Free Markdown ViewerTests"
APP_UNIT_TEST_MODULE_NAME="Free_Markdown_ViewerTests"
APP_UI_TEST_TARGET_NAME="Free Markdown ViewerUITests"
APP_UI_TEST_MODULE_NAME="Free_Markdown_ViewerUITests"
APP_REPO_SLUG="swift-markdown-viewer"
APP_MARKETING_URL="https://www.matthewpaulmoore.com/apps/free-markdown-viewer"
APP_SUPPORT_URL="https://www.matthewpaulmoore.com/apps/free-markdown-viewer/support"
APP_SUPPORT_DOC_PATH="docs/release/free-markdown-viewer-support.md"
APP_SKU="FREEMD"
